[build]
  command = "npm run netlify:build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Debug redirects header for troubleshooting
[[headers]]
  for = "/*"
  [headers.values]
    X-Netlify-Debug = "true"

# Try first with the dedicated login function (most reliable)
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/login"
  status = 200
  force = true

# Try the index function next

# Fallback to other login routes if needed
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth/login"
  status = 200
  force = true

# Third alternative for login endpoint
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

# Final fallback for login endpoint
[[redirects]]
  from = "/.netlify/functions/auth/login"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

# Special case for the me endpoint
[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/auth/me"
  status = 200
  force = true

# Health check through index function
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/index/api/health"
  status = 200
  force = true

# Redirect for auth endpoints specifically to auth function
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

# Redirect for all other API endpoints to server function or index as backup
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Final API fallback to index function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true

# Serve the frontend for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 