[build]
  command = "npm run netlify:build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Special case for the specific login endpoint with direct route
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth/login"
  status = 200
  force = true

# Redirect for auth endpoints specifically to auth function
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

# Redirect for health check endpoints
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/server/api/health"
  status = 200
  force = true

# Redirect for all other API endpoints to server function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Serve the frontend for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 